### ISSUE TITLE
utils script doesn't get to adding data to the database

### ISSUE THREAD

**Issue by mpmckenna8** [mapbox/natural-earth-tm2#4]
When running the utils script it echoes

Setting up PostGIS database...
Downloading Natural Earth Data (213MB)...

Then returns to the bash prompt.  Looks like things set up more or less correctly in postgres:

![psqlshg](https://cloud.githubusercontent.com/assets/1895795/4181015/2ae03b32-370b-11e4-9c4e-180974d3fa27.png)

Using postgres 9.3.4. Not sure what I'm doing wrong.

**Comment by ajashton** [comment]
Looks like either the download or unzip step is failing. Can you remove the first `q` from each of [these two lines](https://github.com/mapbox/natural-earth-tm2/blob/78d38c04df6dab3243af2809199c5e7edb77f9a1/util/setup_db.sh#L25-L26), re-run the script as `bash -x ./util/setup_db.sh`, and post the terminal output back here?

**Comment by mpmckenna8** [comment]
Looks like it's not downloading the shizam.

![postloudergit](https://cloud.githubusercontent.com/assets/1895795/4212867/1a97eca4-38a8-11e4-8261-190a1ea68038.png)

But I have figured out how to hook mapbox-studio up to postgres which was my goal anyhow.  

Thanks for the great examples AJ, even if I can't always get em' to work.

**Comment by mpmckenna8** [comment]
Aha, It does go when I tell it to download from http://naciscdn.org/naturalearth/packages/natural_earth_vector.sqlite.zip

**Comment by mpmckenna8** [comment]
Made it so I get to this error when it's trying to do post-processing: 

```
Post-processing...
ERROR:  GEOSPointOnSurface: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -18148719.28731199 -19193244.511460774 at -18148719.28731199 -19193244.511460774
```

I think this pull request addresses it If you could merge:
https://github.com/mapbox/natural-earth-tm2/pull/2

**Comment by ajashton** [comment]
Ok, I've updated the URL and merged that pull request so all should be well now.
