### ISSUE TITLE
Import Natural Earth to PostGIS report error

### ISSUE THREAD

**Issue by btcnash** [mapbox/natural-earth-tm2#5]
FAILURE:
Unable to open datasource `~/Documents/natural_earth_vector.sqlite' with the following drivers.
  -> ESRI Shapefile
  -> MapInfo File
  -> UK .NTF
  -> SDTS
  -> TIGER
  -> S57
  -> DGN
  -> VRT
  -> REC
  -> Memory
  -> BNA
  -> CSV
  -> NAS
  -> GML
  -> GPX
  -> LIBKML
  -> KML
  -> GeoJSON
  -> Interlis 1
  -> Interlis 2
  -> GMT
  -> GPKG
  -> SQLite
  -> DODS
  -> WAsP
  -> MDB
  -> OGDI
  -> PostgreSQL
  -> PCIDSK
  -> OpenFileGDB
  -> XPlane
  -> AVCBin
  -> AVCE00
  -> DXF
  -> Geoconcept
  -> GeoRSS
  -> GPSTrackMaker
  -> VFK
  -> PGDump
  -> OSM
  -> GPSBabel
  -> SUA
  -> OpenAir
  -> PDS
  -> WFS
  -> SOSI
  -> HTF
  -> AeronavFAA
  -> EDIGEO
  -> GFT
  -> GME
  -> SVG
  -> CouchDB
  -> Idrisi
  -> ARCGEN
  -> SEGUKOOA
  -> SEGY
  -> XLS
  -> ODS
  -> XLSX
  -> ElasticSearch
  -> CartoDB
  -> SXF

**Comment by maiden71** [comment]
HI ! 
I have exactly the same problem ... Is there now a solution ? 

Thank's ! =)
