### ISSUE TITLE
Zoom level conditionals does not affect data

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/natural-earth-tm2#7]
Hi! I'm trying to display landusage from osm database (imported with imposm). So I want to display simplyfied data on different zoom levels. I used custom function `z` with mapnik `!scale_denominator!`, but it seems, that it does not affect on data.

![2015-05-06 13 53 06](https://cloud.githubusercontent.com/assets/533564/7490221/eb9d1576-f3f7-11e4-800a-2696434b2eae.png)

Here is Mapbox Studio screenshot — there are all 3 landusage layers displayed on 13 zoom level. But I want to display data only from `osm_landusages` table.

``` sql
( SELECT * FROM (
    -- landuse_gen0
    SELECT geometry, type, area
    FROM osm_landusages_gen0
    WHERE geometry && !bbox!
    AND CASE
      WHEN z(!scale_denominator!) > 3 THEN TRUE
      WHEN z(!scale_denominator!) <= 9 THEN TRUE
    END

    -- landuse_gen1
    UNION ALL
    SELECT geometry, type, area
    FROM osm_landusages_gen1
    WHERE geometry && !bbox!
    AND CASE
      WHEN z(!scale_denominator!) > 9 THEN TRUE
      WHEN z(!scale_denominator!) <= 12 THEN TRUE
    END

    -- landuse
    UNION ALL
    SELECT geometry, type, area
    FROM osm_landusages
    WHERE geometry && !bbox!
      AND z(!scale_denominator!) > 12
  ) AS QUERY
 ORDER BY area DESC
) AS data
```

What am I missing? Thanks!

**Comment by ajashton** [comment]
`CASE` statements are used to check if _any_ of the `WHEN` comparisons are true, not that _all_ of them are true. To compare the zoom level against ranges you could use `BETWEEN` instead:

``` sql
( SELECT * FROM (
    -- landuse_gen0
    SELECT geometry, type, area
    FROM osm_landusages_gen0
    WHERE geometry && !bbox!
    AND z(!scale_denominator!) BETWEEN 4 AND 9

    -- landuse_gen1
    UNION ALL
    SELECT geometry, type, area
    FROM osm_landusages_gen1
    WHERE geometry && !bbox!
    AND z(!scale_denominator!) BETWEEN 10 AND 12

    -- landuse
    UNION ALL
    SELECT geometry, type, area
    FROM osm_landusages
    WHERE geometry && !bbox!
      AND z(!scale_denominator!) > 12
  ) AS QUERY
 ORDER BY area DESC
) AS data
```

**Comment by stepankuzmin** [comment]
Thanks @ajashton! Now it works as expected.

**Comment by georgbachmann** [comment]
Hm... for me the `z(!scale_denominator!)` works as expected if my zoom is below 7... with any number >= 7 it's not working any more?!? any ideas?

**Comment by ajashton** [comment]
@georgbachmann you will need to adjust the maxzoom property in the settings panel. For this project it's set to 7 by default, which means when you are looking at any zoom levels higher than that the data is still coming from zoom level 7. See https://www.mapbox.com/guides/source-manual/#overzooming

**Comment by georgbachmann** [comment]
@ajashton awesome!!! worked!!! thanks!!!
